### ISSUE TITLE
Suggestion - Support for randomivpercent as a reward spec

### ISSUE THREAD

**Issue by SirDoof** [EnvyWare/EnvyHunt#15]
Looks like the `randomivpercent` doesn't currently work in `reward-specs` and can't apply the spec on the caught Pokémon.
Would be a great addition :)

**Comment by danorris709** [comment]
How would this apply?

Currently the randomivpercent spec selects a random number between the two given arguments and then checks if the Pokemon has an IV percentage equal to that. How would it work? 

Perhaps it should take the percentage, X, and then apply the following function
```
iv = (X / 100) * 31
```
So then all 6 IVs would be equal?

**Comment by SirDoof** [comment]
That'd be fine for that. I think I confused it and was thinking of a different spec.

Specifically, this `numivs` spec from flashspec: https://github.com/Flashback083/FlashSpec/blob/master/src/main/java/fr/flashback083/flashspec/Specs/IvsSpec/NumIVs.java

This spec sets how much ivs at 31 the Pokémon WILL have. For example, `numivs:3` means the Pokémon will have 3 ivs at 31.
So a spec like this for a reward spec would be a good alternative to the `max_iv` spec because rewarding 6iv Pokémon isn't always a good idea imo.
