### ISSUE TITLE
Missing documentation - Blacklist and whitelist pokémon from hunts

### ISSUE THREAD

**Issue by Marco02Arduino** [EnvyWare/EnvyHunt#20]
Hi, I saw that in the old versions of EnvyHunt it was possible to create blacklists and whitelists for the pokemon that could be hunted, is it possible to do it in the new versions too (>4.0.0)? If it is possible, how can this be configured? Thanks in advance for the support.

PS: The *.yml extension is not supported by github, so I uploaded the config files with the *.txt extension

[config.txt](https://github.com/EnvyWare/EnvyHunt/files/10713450/config.txt)
[guis.txt](https://github.com/EnvyWare/EnvyHunt/files/10713451/guis.txt)

**Comment by danorris709** [comment]
I think support was added in the latest version
