### ISSUE TITLE
RandomGender Spec Can Give Impossible Genders

### ISSUE THREAD

**Issue by Mikirae** [EnvyWare/EnvyHunt#22]
Pokemon whose only genders are Male and Female are able to have a Genderless Requirement in Hunts
![image](https://github.com/EnvyWare/EnvyHunt/assets/24925669/34f30277-e4bc-48fc-b63b-a06af140b85b)

**Comment by danorris709** [comment]
This is just a visual bug. Technically what it means is that it will accept either Male or Female for this pokemon

**Comment by Mikirae** [comment]
Any way I could at least change the lang on that then? Don't see anywhere for that but I'm also known to be blind
