### ISSUE TITLE
Start Commands Only Activated After Time Out

### ISSUE THREAD

**Issue by Mikirae** [EnvyWare/EnvyHunt#24]
The start commands aren't actually activated upon someone successfully catching a hunt and starting a new one. They seem to only work if the hunt expires from no one catching the hunt Pokemon.

**Comment by danorris709** [comment]
This isn't a bug - the next hunt begins when the previous one times out?

**Comment by Mikirae** [comment]
But it doesn't do it when someone catches a Hunt Pokemon, which also starts the next hunt.

**Comment by danorris709** [comment]
Oh I understand what you mean now

**Comment by danorris709** [comment]
Fixed for next version
