### ISSUE TITLE
[EnvyHunts] Errors with IVs and Particles

### ISSUE THREAD

**Issue by Lieren-HuntGhosts** [EnvyWare/EnvyHunt#25]
Noticed that when using "randomivpercentage" it will select an iv percentage number as usual, but will make that number the only one accepted by the hunt, so if the hunt chooses the number 15, only 15% IVs pokemon will be accepted, nothing above or below, not as in previous versions where anything from 15% or above was fine. Is there any way to make this work as in previous versions?

Also, in the code you need to have a "- random" line with nothing else for it to work, for example:
```
requirement-specs:
- random
- randomivpercent:10-20

```
And lastly the particle effects only apply to pokemon valid for the hunt, if it doesnt meet the IV requirements for example even though being the same species, it doesn't have the particles. This tells the players what pokemon to ignore or not withing the same species

**Comment by danorris709** [comment]
Fixed all these for the next version
