### ISSUE TITLE
[EnvyHunt] ''Gender'' error and ''Growths'' error

### ISSUE THREAD

**Issue by Lieren-HuntGhosts** [EnvyWare/EnvyHunt#27]
**1st Issue:**
When using the "- randomgender" config, it can randomly choose "genderless" for pokemon that always have gender.

Either make always choose a gender and ban genderless pokemons in config, or make it search for a pokemon with gender when that option is used please.

**2nd Issue:**
When using "randomgrowths" and reloading the hunts several times, the Hunt's GUI stops showing up. This is an example of what I've been using:

> "- randomgrowths:pigmy,runt,small,ordinary,huge,giant,enormous:5"

**Comment by danorris709** [comment]
https://github.com/EnvyWare/EnvyHunt/issues/22
